# Starts a test DB to generate JOOQ classes
version: '3.8'
services:
  db:
    image: "mysql:8.0.20"
    ports:
      - "4306:3306"
    volumes:
      - ./src/test/resources/io/bootique/jooq:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root

